name: Deploy to Server
on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies and build
        run: |
          npm install
          npm run build 

      - name: Compress build files
        run: |
          cd dist
          tar -czf ../dist.tar.gz ./*
          cd ..
          ls -lh dist.tar.gz

      - name: Deploy compressed file
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          source: "dist.tar.gz"
          target: "/tmp/"

      - name: Extract and deploy on server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            echo "开始解压部署..."
            rm -rf {{ secrets.DEPLOY_DIR }}/*
            tar -xzf /tmp/dist.tar.gz -C {{ secrets.DEPLOY_DIR }}
            rm -f /tmp/dist.tar.gz
            chmod -R 755 {{ secrets.DEPLOY_DIR }}
            echo "部署完成！"